### Listar todas as tarefas
GET http://localhost:8080/tasks
Accept: application/json


### Adicionar uma nova tarefa
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "title": "Wake up",
    "description":, "wake up at 8 am"

}

### Listar uma tarefa especifica
GET http://localhost:8080/tasks/2
Accept: application/json

### Editar uma tarefa 
PUT http://localhost:8080/tasks/1 
Content-Type: application/json

{
    "title": "Go to sleep",
    "description":, "go to sleep at 8 pm"

}

### Status da tarefa
PATCH http://localhost:8080/tasks/3/status
Content-Type: application/json

{}

### Deletar uma tarefa
DELETE http://localhost:8080/tasks/1

### Simular a leitura de multiplas tarefas
POST http://localhost:8080/simulate-reading
Content-Type: application/json

{
  "task_ids": [1, 2, 3]
}
