services:
  db:
    image: mysql:8.0
    container_name: todolist
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql



  # app:
  #   build: .
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 33060
  #     DB_USER: root
  #     DB_PASSWORD: password
  #     DB_NAME: todolist
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"

    
